# Generated by Django 4.1.5 on 2023-02-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_review_desc_remove_review_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
