# Generated by Django 4.1.5 on 2023-02-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_address_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='reviewed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
