# Generated by Django 4.1.5 on 2023-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_profile_address_profile_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
