# Generated by Django 4.1.5 on 2023-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
