# Generated by Django 4.1.5 on 2023-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_orderdetail_amount_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
